export { default as Payment1 } from '@assets/images/payment-1.png'
export { default as Payment2 } from '@assets/images/payment-2.png'
export { default as Payment3 } from '@assets/images/payment-3.png'
export { default as Payment4 } from '@assets/images/payment-4.png'
export { default as Payment5 } from '@assets/images/payment-5.png'
export { default as Payment6 } from '@assets/images/payment-6.png'
export { default as Payment7 } from '@assets/images/payment-7.png'
export { default as Payment8 } from '@assets/images/payment-8.png'

export { default as Carrier1 } from '@assets/images/carrier-1.png'
export { default as Carrier2 } from '@assets/images/carrier-2.png'
export { default as Carrier3 } from '@assets/images/carrier-3.png'
export { default as Carrier4 } from '@assets/images/carrier-4.png'
export { default as Carrier5 } from '@assets/images/carrier-5.png'
export { default as Carrier6 } from '@assets/images/carrier-6.png'
export { default as Carrier7 } from '@assets/images/carrier-7.png'
export { default as Carrier8 } from '@assets/images/carrier-8.png'
export { default as Carrier9 } from '@assets/images/carrier-9.png'
export { default as Carrier10 } from '@assets/images/carrier-10.png'
export { default as Carrier11 } from '@assets/images/carrier-11.png'

export { default as App1 } from '@assets/images/app-1.png'
export { default as App2 } from '@assets/images/app-2.png'
export { default as App3 } from '@assets/images/app-3.png'
export { default as App4 } from '@assets/images/app-4.png'
