export { default as Home } from '@/pages/home'
export { default as Register } from '@/pages/register'
export { default as Login } from '@/pages/login'
export { default as Profile } from '@/pages/profile'
export { default as ProductDetails } from '@/pages/[id]'
